app:
  # URLs for public IP API. One for IPv4 and IPv6 addresses
  # Must return IP as string in body of response
  publicIP4Api: "https://api.ipify.org"
  publicIP6Api: "https://api6.ipify.org"

  # Domain that will be queried and updated if local IP has changed
  domainName: "example.com"

  # DNS Provider. Currently only supports "Google Cloud DNS"
  dnsProvider: "Google Cloud DNS"

gcpDNS:
  # Name of GCP project
  projectName: "" 
  # Name or ID of GCP DNS managed zone
  zoneName: ""
  # Time to live - amount of time for DNS record to be cached - value is in seconds and must be an integer
  ttlValue: 300 