# Creates a release whenever a new tag is pushed to the repository.
on: 
  push:
    tags: 
      - 'v*'
name: New Release
jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      working-directory: ./
      run: go build -v -o ddns-client-Linux-x64
    - name: Create Archive
      working-directory: ./
      run: |
        cp ./services/ddns-client.service ./
        cp ./services/ddns-client.timer ./
        tar -cvzf ddns-client-Linux-x64.tar.gz ddns-client.service ddns-client.timer ddns-client-config-sample.yaml ddns-client-Linux-x64
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./ddns-client-Linux-x64.tar.gz
        draft: false
        prerelease: false