name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.x
        check-latest: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
